version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000

  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    volumes:
      - .:/app
    command: streamlit run UI_app.py --server.port 8501 --server.address 0.0.0.0

volumes:
  redis_data: